sudo: required
services:
  - docker

before_install:
  - docker build -t kevin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kevin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-2"
  butket_name: "elasticbeanstalk-us-east-2-181095187562"
  butket_path: "socker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY